const app = getApp()
let config = app.globalData
Component({
  props:{
    showFlag:false,
    onCloseSpec:()=>{},//隐藏自定义规格弹窗
    onGomakephoto:()=>{} //选中自定义去制作图片
  },
  data: {
    focusedInput:'',
    errorTip:'',
    params:{
      width:'',
      height:'',
      max:'',
      min:'',
      ppi:300
    },
    isIos:false
  },
  didMount(){
    this.setData({
      isIos:config.isIos
    })
  },
  methods:{
    onShowpop(){
      console.log("点击遮罩层不消失")
    },
    propt(type,cot){
      my.prompt({
        title: cot,
        success: (result) => {
          let {ok,inputValue}=result
          my.pageScrollTo({
            scrollTop:1
          });
          ok&&this.setData({
            [type]:inputValue
          })
        }
      })
    },
    inputFocus:function(e){
      this.setData({
        focusedInput:e.currentTarget.dataset.index
      })
    },
    recordWidth:function(e){
      this.setData({
        "params.width":e.detail.value
      })
    },
    recordHeight:function(e){
      this.setData({
        "params.height":e.detail.value
      })
    },
    recordMax:function(e){
      this.setData({
        "params.max":e.detail.value
      })
    },
    recordMin:function(e){
      this.setData({
        "params.min":e.detail.value
      })
    },
    recordPPI:function(e){
      this.setData({
        "params.ppi":e.detail.value
      })
    },
    showDPI:function(){
      my.alert({
        title: 'DPI是什么？',
        content:'DPI(Dots Per Inch)是指印刷设备的分辨率，对于电子照片，DPI与PPI是等值的。无特殊要求的照片直接使用默认的300DPI即可' 
      });
    },
    sumbit:function(){
      let pdata = this.data.params
      if(!pdata.width){
        this.setData({
          errorTip:"照片宽度不能为空"
        })
        return
      }
      if(!pdata.height){
        this.setData({
          errorTip:"照片高度不能为空"
        })
        return
      }
      if(!(/^[1-9]\d*$/.test(+pdata.width))){
        this.setData({
          errorTip:"宽必须为数字"
        })
        return
      }
      if(!(/^[1-9]\d*$/.test(+pdata.height))){
        this.setData({
          errorTip:"高必须为数字"
        })
        return
      }
      if(pdata.width<70||pdata.width>1200){
        this.setData({
          errorTip:"照片宽度必须在70~1200px"
        })
        return
      }
      if(pdata.height<100||pdata.height>1600){
        this.setData({
          errorTip:"照片高度必须在100~1600px"
        })
        return
      }
      if(pdata.width/pdata.height>1||pdata.width/pdata.height<0.5){
        this.setData({
          errorTip:"照片宽高比要在0.5~1"
        })
        return
      }
      if(pdata.min){
        if(pdata.min==0){
          this.setData({
            errorTip:"文件最小值不能为0"
          })
          return
        }
        if(!(/^[1-9]\d*$/.test(+pdata.min))){
          this.setData({
            errorTip:"文件最小值必须为数字"
          })
          return
        }
        if(pdata.min>5120){
          this.setData({
            errorTip:"文件最小值不能超过5120KB"
          })
          return
        }
      }
      if(!(/^[1-9]\d*$/.test(pdata.ppi))){
        this.setData({
          errorTip:"ppi必须为数字"
        })
        return
      }
      if(pdata.ppi>600){
        this.setData({
          errorTip:"ppi不能大于600"
        })
        return
      }
      if(pdata.max){
        if(pdata.max==0){
          this.setData({
            errorTip:"文件最大值不能为0"
          })
          return
        }
        if(!(/^[1-9]\d*$/.test(+pdata.max))){
          this.setData({
            errorTip:"文件最大值必须为数字"
          })
          return
        }
        if(pdata.max>5120){
          this.setData({
            errorTip:"文件最大值不能超过5120KB"
          })
          return
        }
      }
      if(pdata.min&&pdata.max&&+pdata.max<+pdata.min){
        this.setData({
          errorTip:"文件最大值不能小于最小值"
        })
        return
      }
      console.log(pdata)
      let {
        width,
        height,
        max,
        min,
        ppi
      }=pdata
      config.makePhotoInfo.spec_id=""
      config.makePhotoInfo.file_size_max=max*1024
      config.makePhotoInfo.file_size_min=min*1024
      config.makePhotoInfo.ppi=ppi
      config.makePhotoInfo.width_px=width
      config.makePhotoInfo.height_px=height
      config.makePhotoInfo.specName="自定义"
      config.makePhotoInfo.width_mm = 0
      config.makePhotoInfo.height_mm=0
      config.makePhotoInfo.background_color=config.defaultColor
      config.makePhotoInfo.print=0//自定义规格不能有冲印
      this.reset()
      this.props.onGomakephoto()
    },
    onCancel(){
      this.reset()
      this.props.onCloseSpec()
    },
    reset:function(){
      this.setData({
        focusedInput:'',
        errorTip:'',
        params:{
          width:'',
          height:'',
          max:'',
          min:'',
          ppi:300
        }
      })
    }
  }
})